### ISSUE TITLE
Not working until close and re-run npm run start

### ISSUE THREAD

**Issue by tfsomrat** [4044ever/hugo-boilerplate-tailwind-jit#1]
It's not working properly, it needs to be restarted the command and then clear the browser cache to work properly.

**Comment by 4044ever** [comment]
I noticed cache issues. Will have have a closer look and investigate.

**Comment by tfsomrat** [comment]
Nope, it doesn't work. And i wanna make sure that, it's not only cache issue. it's gulp issue also. because it doesn't generate the proper css until you close the gulp and run again. then comes the cache issue, which maybe solved by --noHTTPCache

**Comment by 4044ever** [comment]
I am not sure about the "_gulp doesn't generate the proper css_". How does that effect the dev? I mean, in what way? Gulp is something I just installed without looking much into it. On localhost:1313 I do get a minified *.css - and the desired css styles. 
In any case, thank you for the feedback.

**Comment by tfsomrat** [comment]
I mean when I add a new class in the HTML layout, the proper css is not added in the css file, until I close the `npm run start` by pressing `ctrl+c` and run it again. do you get it now? It may be the gulp issue, or maybe the jit issue, I don't know. what I know is, it's not working for sure.

**Comment by 4044ever** [comment]
Since I am working on a website right now I can reproduce the problem/error. I need to dig a bit deeper to learn what's going wrong there. In the meantime, if you have a hint please let me know.
